export { SITE_URL, SITE_NAME, CONTACT, WHATSAPP, GOOGLE_SITE_VERIFICATION } from "./site-config.js";
export type { Locale, PageId, FleetVehicle, FaqItem } from "./types.js";
export { NAV_ITEMS } from "./content/nav.js";
export { HOME_META } from "./content/home.js";
export { ABOUT_META } from "./content/about.js";
export { FLEET_META, FLEET_VEHICLES } from "./content/fleet.js";
export { FAQ_ITEMS } from "./content/faq.js";
export { renderHomePage } from "./render/pages/home.js";
export { renderAboutPage } from "./render/pages/about.js";
export { renderFleetPage } from "./render/pages/fleet.js";
export { renderRobotsTxt, renderSitemapXml } from "./seo/sitemap.js";
